apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: caching-service-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: caching-service-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 92
